import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Housinger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // corsMiddleware(this);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="bottom-left" />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            {children}
          </Providers>
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
        {/* <footer className="flex justify-center items-center py-10">
          Footer Here!
        </footer> */}
      </body>
    </html>
  );
}
